name: Picture Compare
template: D:/code/image/src/template
image_package: [img1, img2, img3 ,img4]
database: None
project_dir:  D:/code/image/
static_dir: img/
test_compare_img: 1.jpg
project_port: 8888