name: Picture Compare
template: /Users/liyang/Code/image/src/template
database: None
project_dir:  /Users/liyang/Code/image/
static_dir: img/
test_compare_img: 1.jpg
project_port: 8888
server_url: http://localhost:8888
storage_index_db: /Users/liyang/Code/image//img/imgdb/img.db
# test
image_package: [img1, img2, img3 ,img4]