# coding:utf-8

NAME = 'NAME'
TEMPLATE = 'TEMPLATE'
IMAGE_PACKAGE = 'IMAGE_PACKAGE'
DATABASE = 'DATABASE'

PROJECT_DIR = 'PROJECT_DIR'
STATIC_DIR = 'STATIC_DIR'

TEST_COMPARE_IMG = 'TEST_COMPARE_IMG'

PROJECT_PORT = 'PROJECT_PORT'

SERVER_URL = 'SERVER_URL'

STORAGE_INDEX_DB = 'STORAGE_INDEX_DB'
